export default () => {
  return [
    {
      'directoryId': 1,
      'title': 'First',
      'description': 'First Notice',
      'tags': ['one', 'two', 'three '],
      id: 1,
      position: 1,
    },
    {
      'directoryId': 1,
      'title': 'Second',
      'description': 'Second Notice',
      'tags': ['one', 'two', 'three '],
      id: 2,
      position: 2,
    },
    {
      'directoryId': 1,
      'title': 'Third',
      'description': 'Third Notice',
      'tags': ['one', 'two', 'three '],
      id: 3,
      position: 3,
    },
    {
      'directoryId': 2,
      'title': 'Fourth',
      'description': 'Fourth Notice \nhey there new line',
      'tags': ['one', 'two', 'three '],
      id: 4,
      position: 1,
    },
    {
      'directoryId': 2,
      'title': 'Fifth',
      'description': 'Fifth Notice',
      'tags': ['one', 'two', 'three '],
      id: 5,
      position: 2,
    },
    {
      'directoryId': 3,
      'title': 'Sixth',
      'description': 'Sixth Notice',
      'tags': ['one', 'two', 'three '],
      id: 6,
      position: 1,
    },
    {
      'directoryId': 3,
      'title': 'Seventh',
      'description': 'Seventh Notice',
      'tags': ['one', 'two', 'three '],
      id: 7,
      position: 3,
    },
    {
      'directoryId': 3,
      'title': 'Eighth',
      'description': 'Eighth Notice',
      'tags': ['one', 'two', 'three '],
      id: 8,
      position: 2,
    },
    {
      'directoryId': 4,
      'title': 'Nineth',
      'description': 'Nineth Notice',
      'tags': ['one', 'two', 'three '],
      id: 9,
      position: 1,
    },
    {
      'directoryId': 4,
      'title': 'Eleventh',
      'description': 'Eleventh Notice',
      'tags': ['one', 'two', 'three '],
      id: 10,
      position: 2,
    },
    {
      'directoryId': 4,
      'title': 'Twelvth',
      'description': 'Twelvth Notice',
      'tags': ['one', 'two', 'three '],
      id: 11,
      position: 3,
    },
    {
      'directoryId': 4,
      'title': 'Thirteenth',
      'description': 'Thirteenth Notice',
      'tags': ['one', 'two', 'three '],
      id: 12,
      position: 4,
    },

  ];
}
