export default {
	ADD_DIRECTORY: 'ADD_DIRECTORY',
	REMOVE_DIRECTORY: 'REMOVE_DIRECTORY',
  	UPDATE_DIRECTORY:'UPDATE_DIRECTORY',
	DIRECTORY_ADDED: 'DIRECTORY_ADDED',
	TOGGLE_DIR: 'TOGGLE_DIR',
	HEADING_WILL_CHANGE: 'HEADING_WILL_CHANGE',
	DIRECTORY_HEADING_WAS_CHANGED: 'DIRECTORY_HEADING_WAS_CHANGED',

	ADD_NOTICE: 'ADD_NOTICE',
	REMOVE_NOTICE: 'REMOVE_NOTICE',
  	UPDATE_NOTICE:'UPDATE_NOTICE',
	LOAD_NOTICE: 'LOAD_NOTICE',	
	LOAD_NOTICES: 'LOAD_NOTICES',
	REMOVE_TAG: 'REMOVE_TAG'
}
