export default {
  TOGGLE_DIR: 'TOGGLE_DIR',
  HEADING_WILL_CHANGE: 'HEADING_WILL_CHANGE',
  DIRECTORY_HEADING_WAS_CHANGED: 'DIRECTORY_HEADING_WAS_CHANGED',

  LOAD_NOTICES: 'LOAD_NOTICES',
  LOAD_NOTICE_BY_ID: 'LOAD_NOTICE_BY_ID',
  ADD_NOTICE: 'ADD_NOTICE',
  UPDATE_NOTICE: 'UPDATE_NOTICE',
  DELETE_NOTICE: 'DELETE_NOTICE',

  LOAD_DIRECTORIES: 'LOAD_DIRECTORIES',
  ADD_DIRECTORY: 'ADD_DIRECTORY',
  UPDATE_DIRECTORY: 'UPDATE_DIRECTORY',
  DELETE_DIRECTORY: 'DELETE_DIRECTORY',
}
