export default {
  DIRECTORY_ADDED: 'DIRECTORY_ADDED',
  TOGGLE_DIR: 'TOGGLE_DIR',
  HEADING_WILL_CHANGE: 'HEADING_WILL_CHANGE',
  DIRECTORY_HEADING_WAS_CHANGED: 'DIRECTORY_HEADING_WAS_CHANGED',

  LOAD_NOTICES: 'LOAD_NOTICES',
  ADD_NOTICE: 'ADD_NOTICE',
  UPDATE_NOTICE: 'UPDATE_NOTICE',
  DELETE_NOTICE: 'DELETE_NOTICE',
  UPDATE_NOTICE_POSITION: 'UPDATE_NOTICE_POSITION',

  LOAD_DIRECTORIES: 'LOAD_DIRECTORIES',
  ADD_DIRECTORY: 'ADD_DIRECTORY',
  UPDATE_DIRECTORY: 'UPDATE_DIRECTORY',
  DELETE_DIRECTORY: 'DELETE_DIRECTORY',
  UPDATE_DIRECTORY_NAME: 'UPDATE_DIRECTORY_NAME'
}
